---
title: "MPT solution"
author: "Joachim Vandekerckhove"
output:
  beamer_presentation:
    incremental: yes
header-includes:
  - \input{includes/beamerpheader.tex}
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "../pdf")
  })
---


## One-High Threshold Model ~ results
```{r fig.width = 4.5, fig.height = 3.5, fig.align='center', message=FALSE, echo=TRUE, results='hide', jags-1}
library(rjags)

 data <- list(
  hits    = c(  8,  9, 14, 14, 13,  8, 13, 12, 11,
                4,  8, 13, 15, 12, 11,  9,  5,  5,
                6, 15, 11, 14, 12, 12, 11,  1, 14,
               13,  7, 11, 12,  8, 11) ,
  fas     = c( 4, 4, 0, 1, 2, 0, 3, 1, 3, 0, 0, 1,
               0, 0, 0, 0, 1, 0, 3, 0, 0, 1, 2, 1,
               2, 0, 0, 0, 2, 1, 2, 0, 2) ,
  nPeople = 33 ,
  nOld    = 15 ,
  nNew    = 15 )
```

##

```{r fig.width = 4.5, fig.height = 3.5, fig.align='center', message=FALSE, echo=TRUE, results='hide', jags-2}
modelString = "
  # MPT single high threshold
  model{
    for (i in 1:nPeople){
      hits[i] ~ dbin(thetaHit, nOld)
      fas[i]  ~ dbin(thetaFA , nNew)
    }
    thetaHit = rho + (1-rho)*gamma
    thetaFA  = gamma
    rho   ~ dunif(0, 1)
    gamma ~ dunif(0, 1)
  }
"
modelFile <- "mpt_solution.jags"
writeLines( modelString , con = modelFile)
```

##

```{r fig.width = 4.5, fig.height = 3.5, fig.align='center', message=FALSE, echo=TRUE, results='hide', jags-3}
jagsModel = jags.model( file     = modelFile,
                        data     =      data,
                        n.chains =        3 ,
                        n.adapt  =      500 )
set.seed(0)
samples = coda.samples( jagsModel,
                        variable.names = c("gamma",
                                           "rho"),
                        n.iter         = 1000 )
```

```{r, echo=TRUE, render=FALSE, include=TRUE, eval=FALSE, figure-0}
plot(samples)
```

## One-High Threshold Model ~ figures
```{r, echo=FALSE, figure-1}
plot(samples)
```

## One-High Threshold Model ~ summary statistics
\footnotesize
```{r, echo=TRUE, summary}

summary(samples)$statistics

summary(samples)$quantiles
```

## One-High Threshold Model ~ convergence
\footnotesize
```{r, echo=TRUE, convergence}

effectiveSize(samples)

gelman.diag(samples)
```
